### ISSUE TITLE
auto-generated file is a bit overbearing

### ISSUE THREAD

**Issue by IlanCosman** [nvuillam/mega-linter#364]
This might come across as silly 😄 

As a semi-advanced user of Github Actions, I found the auto-generated CI action to be rather overbearing. It's this dense 90 line file that just looks like an absolute mess, especially the 300 character `if` lines. This was really off-putting to me when what I wanted, and all that was necessary for my use case, was more like this:

```yaml
mega-linter:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2

    - uses: nvuillam/mega-linter/flavors/documentation@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DISABLE_LINTERS: SPELL_CSPELL
```

I'm sure the auto-generated file would work fine. In fact, it probably works better than what I have here. But my reaction in the moment was an annoyed "What the hell is this," and I still wouldn't want to use that file in my repo.

I know this is illogical, but I'd also bet that some others will feel similarly.

P.S. I really love mega-linter, thanks for your hard work 👍
