### ISSUE TITLE
GitHub Action only considers major version when pulling Docker image

### ISSUE THREAD

**Issue by ottumm** [nvuillam/mega-linter#509]
**Describe the bug**

Using the Mega-Linter GitHub Action, there is no way to completely specify a full version, because it always pulls the `v4` tagged image. See https://github.com/nvuillam/mega-linter/blob/510ad37a0456a762eadec0d992aaabcaf4cbc615/flavors/python/action.yml#L8-L10

This is a problem because I need to be able to ensure that linters provide consistent behavior across runs.

I'm not sure if it's possible to know which git tag was used to refer to an action from within the action (I suspect it's not), but if not then perhaps a `version` parameter could be added to the action so that the correct tag could be pulled. I'm happy to open a pull request with that solution if it sounds good.

**To Reproduce**

Use the following in a `.github/workflows` yaml:

```yaml
name: tests
on:
  push:
    branches-ignore: [master]

jobs:
  lint:
    runs-on: [ubuntu-20.04]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: mega-lint
        uses: nvuillam/mega-linter@v4.3.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Expected behavior**

I expected this action to pull the Docker image with tag `v4.34.0`, but instead it pulls tag `v4`, which is a different image.
