### ISSUE TITLE
Question for configuration 

### ISSUE THREAD

**Issue by milica-nikolic** [nvuillam/mega-linter#549]
Hello everyone!

I tried to implement Mega-Linter in my project but there are some folder that I would like to exlude from linting procces because there are gonna be in future exluded from project after refactoring is done.

This is example of my yaml file, I set up configuration like this but still I can find those file being linted in logs of pipeline.

```
stages:
  - test

test:mega-linter:
  stage: test
  image: nvuillam/mega-linter:v4
  allow_failure: true
  script: [ "true" ]
  variables:
    DEFAULT_WORKSPACE: $CI_PROJECT_DIR
    DEFAULT_BRANCH: ci-initial-setup
    FILTER_REGEX_EXCLUDE: '(CBPm/CBPm/Client/)'
  artifacts:
    when: always
    paths:
      - report
    expire_in: 1 week
  tags:
    - dev
    - docker
    - mw
```

Can someone please tell me what did I wrong ?
I have implemented this in gitlab pipeline through .gitlab-ci.yml file which is in root of my repo.

Later this day I tried many ways and used this variables ADDITIONAL_EXCLUDED_DIRECTORIES, FILTER_REGEX_EXCLUDE, FILTER_REGEX_INCLUDE that where set up in Setting/ CI-CD part of project or in .gitlab-ci.yml file or in file .mega-linter.yml to narrow focus of scanning process but still every time in logs it would be said that mega-linter is skiping those files and after that pipeline would be full of logs from scanning those files.
Also tool exluded listed linters but not files. Is there some kind of bug in tool currently ?

This is my .mega-linter.yml file now:

# Configuration file for Mega-Linter
```

DISABLE:
  - SPELL
DISABLE_LINTERS:
  - GIT_GIT_DIFF
FILTER_REGEX_EXCLUDE: '(CBPm/CBPm/Client)'
DEFAULT_WORKSPACE: $CI_PROJECT_DIR
DEFAULT_BRANCH: ci-initial-setup
PRE_COMMANDS:
  - command: echo "This is Mega-Linter PRE_COMMAND"
    cwd: "root"
POST_COMMANDS:
  - command: echo "This is Mega-Linter POST_COMMAND"
    cwd: "workspace"
```

Thank you in advance!

**Comment by nvuillam** [comment]
- Please can you try by defining variables in a .mega-lintet.yaml file at the root of your repo ? I think it's easier to investigate

- What are the names of your ignored folders ? The regex can contain different segments separated by a pipe | 
Examples: https://regex101.com/r/rfYwuz/1

- Disabling GIT_GIT_DIFF seems dangerous, it means that you will let pass sources with unsolved git conflicts in CI ^^
- Are you sur the default branch is not something like master or development ? Usually it it the branch where Merge Requests are targetted, not the current branch

Please share your repo if you want me to have a look :)

**Comment by milica-nikolic** [comment]
Thank you for your answer, I really appreciate that!

Now my .gitlab-ci.yml file looks like this:

```
---
stages:
  - test

test:mega-linter:
  stage: test
  image: nvuillam/mega-linter:v4
  allow_failure: true
  script: [ "true" ]
  variables:
    DEFAULT_WORKSPACE: $CI_PROJECT_DIR
    DEFAULT_BRANCH: ci-initial-setup
  artifacts:
    when: always
    paths:
      - report
    expire_in: 1 week
  tags:
    - dev
    - docker
    - mw

```

And this is .mega-linter.yml file:

```

# Configuration file for Mega-Linter

DISABLE:
  - SPELL
FILTER_REGEX_EXCLUDE: '(CBPm/CBPm/Client/)'
```

I couldn't add this two variables in .mega-linter.yml file ( DEFAULT_WORKSPACE and DEFAULT_BRANCH) cause than my pipelines fails immediately which is strange because they are also listed with other variables for that file in documentation.

- I would like at this point to ignore Client folder, path to that folder is CBPm/CBPm/Client on GitLab so I think I specify right path, am I right ?

- I just disable GIT_GIT_DIFF linter for testing purpose, cause I am learning at this point how to use Mega-Linter so I was curious to see will that part of .mega-linter.yml file work

- Cause this is still in stage of implementation, I created my branch from dev and pointed Mega-Linter on that branch. For the future, is it a best practice to point Mega-Linter only on master branch? How does that affects other branches, they will not be included in linting process, only when work from those other branches comes together with master or dev branch we will se results of linting process on that work?

At this point I am not able to share my repo because it is private repo.
