### ISSUE TITLE
Cancellation of previous workflow runs with GH Actions

### ISSUE THREAD

**Issue by lars-reimann** [nvuillam/mega-linter#622]
**Describe the bug**
The [example workflow for GitHub actions](https://raw.githubusercontent.com/nvuillam/mega-linter/master/TEMPLATES/mega-linter.yml) contains the following section:

``` yaml
# Cancel duplicate jobs: https://github.com/fkirc/skip-duplicate-actions#option-3-cancellation-only
cancel_duplicates:
  name: Cancel duplicate jobs
  runs-on: ubuntu-latest
  steps:
    - uses: fkirc/skip-duplicate-actions@master
      with:
        github_token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
```

The intention behind this seems to be to cancel previous workflow runs when a push on the same branch occurs. However, the default behavior of fkirc/skip-duplicate-actions was changed in https://github.com/fkirc/skip-duplicate-actions/pull/93 and the section `#option-3-cancellation-only` mentioned in the comment was subsequently removed in https://github.com/fkirc/skip-duplicate-actions/pull/94. Now it is necessary to specifically set the option `cancel_others`, otherwise previous workflows run until completion.

```yaml
cancel_duplicates:
  name: Cancel duplicate jobs
  runs-on: ubuntu-latest
  steps:
    - uses: fkirc/skip-duplicate-actions@master
      with:
        github_token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
        cancel_others: true
```

It might be advisable to fix this dependency to a specific version (at least major + minor), since they introduce breaking changes with minor version updates.

**To Reproduce**

1. Use example workflow for GitHub Actions (also created by mega-linter-runner)
2. Push to trigger workflow
3. Push again before the previous workflow is done.

**Expected behavior**
Previous workflow runs should be cancelled when new pushes to the branch occur.

**Screenshots**

**Additional context**
