### ISSUE TITLE
eslint ignore patterns ignored

### ISSUE THREAD

**Issue by selfagency** [nvuillam/mega-linter#708]
**Describe the bug**
My `.eslintrc.js` uses a plugin that tells eslint to ignore all the files specified in my `.gitignore`. I also have a series of explicit path exclusions listed in the `.eslintrc.js` under `ignorePatterns`. These directives are being ignored and consequently my lint task is failing.

**To Reproduce**

1. Add `ignorePatterns` to `.eslintrc.js`
2. Add a file inside an ignored folder
3. Run `eslint` and watch it work
4. Deploy it to GitHub, click on Actions, and watch it fail

**Expected behavior**
For `ignorePatterns` to be honored

**Screenshots**

![CleanShot 2021-08-30 at 13 16 36](https://user-images.githubusercontent.com/2541728/131378433-b533503d-d730-4337-a6fc-d4d10e8b5dc8.png)

![CleanShot 2021-08-30 at 13 15 22](https://user-images.githubusercontent.com/2541728/131378339-d426ac82-f3a0-4463-b89f-eb629a75514f.png)

**Comment by nvuillam** [comment]
What is the eslint plugin you use ?
We can probably add it as option :)

**Comment by selfagency** [comment]
[eslint-gitignore](https://www.npmjs.com/package/eslint-gitignore)

**Comment by nvuillam** [comment]
I think that eslint-gitignore is not widely used (yet ?) to be integrated within Mega-Linter

But you can use it anyway by defining a [PRE_COMMAND](https://nvuillam.github.io/mega-linter/configuration/#pre-commands) in your `.mega-linter.yml` file

Please can you try to add:

```yaml
PRE_COMMANDS:
  - command: npm install && npm install -D eslint-gitignore
    cwd: "workspace"   # Will be run at the root of the workspace (usually your repository root)
```

If it does not work, you may also try

```yaml
PRE_COMMANDS:
  - command: npm install && npm install -D eslint eslint-gitignore
    cwd: "workspace"   # Will be run at the root of the workspace (usually your repository root)
```
