### ISSUE TITLE
ESLint couldn't find the plugin "eslint-plugin-jsx-a11y". (a dependency of eslint-config-airbnb)

### ISSUE THREAD

**Issue by davidBernardWefox** [nvuillam/mega-linter#787]
**Describe the bug**
On a nodejs project with airbnb enabled as plugin of eslint. mega-linter failed with 

```
--Error detail:

Oops! Something went wrong! :(

ESLint: 7.32.0

ESLint couldn't find the plugin "eslint-plugin-jsx-a11y".

(The package "eslint-plugin-jsx-a11y" was not found when loaded as a Node module from the directory "/tmp/lint".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-jsx-a11y@latest --save-dev

The plugin "eslint-plugin-jsx-a11y" was referenced from the config file in "--config » eslint-config-airbnb » /node_modules/eslint-config-airbnb/rules/react-a11y.js".

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.


❌ Linted [JAVASCRIPT] files with [eslint]: Found 1 error(s) - (4.68s)
```

**To Reproduce**

create a nodejs project with `eslintrc.json` that enable airbnb like 

```
{
  "extends": ["airbnb", "prettier"],
  "plugins": ["prettier", "jest"],
  "rules": {
    "prettier/prettier": ["error"]
  },
  "env": {
    "jest/globals": true
  }
}
```

and `package.json`with

```
  "devDependencies": {
    "eslint": "^7.32.0",
    "eslint-config-airbnb": "^18.2.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-jest": "^24.4.2",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "^26.6",
    "jest-circus": "^27.0",
    "prettier": "2.3"
  }
```

To reproduce locally  be sure to remove `node_modules`folder then run

```
docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock:rw -v "$PWD:/tmp/lint:rw" nvuillam/mega-linter-javascript:v4
```

**Expected behavior**

to run the airbnb plugin without error, (airbnb plugin is already part of the mega-linter distribution, but maybe dependencies are not fully installed)

**Screenshots**

**Additional context**

- reproducible locally
- reproducible with github-action
- error with v4, v4.46.0

**Comment by davidBernardWefox** [comment]
As a workround, I modified `.github/workflow/mega-linter.yml` by installing missing package before running step mega-linter

```yaml
      - name: HACK run npm install to have eslint-plugin-jsx-a11y (see https://github.com/nvuillam/mega-linter/issues/787)
        run: |
          mv .npmrc .npmrc.old || true
          npm install eslint-plugin-jsx-a11y@latest --no-save
          mv .npmrc.old .npmrc || true

      # Mega-Linter
      - name: Mega-Linter
```
